name: docker

on:
  push:
    branches: [ "master" ]
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5.2.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}      

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5.1.0
      with:
        context: build-tools
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
